/*
 * File: app/view/servicios/otros/resumenplaca.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('siadno.view.servicios.otros.resumenplaca', {
    extend: 'Ext.window.Window',
    alias: 'widget.ServiciosOtrosResumenPlaca',

    autoShow: true,
    height: 600,
    width: 800,
    layout: {
        align: 'stretch',
        type: 'vbox'
    },
    iconCls: 'icon-application_view_list',
    title: 'Resumen por Placa',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    margins: '3 3 3 3',
                    height: 45,
                    id: 'formParametros3',
                    layout: {
                        align: 'stretch',
                        type: 'hbox'
                    },
                    bodyPadding: 10,
                    url: 'clases/interfaces/InterfazRegistroServicios.php',
                    items: [
                        {
                            xtype: 'textfield',
                            flex: 1,
                            fieldLabel: 'Placa del Auto',
                            name: 'placa',
                            listeners: {
                                change: {
                                    fn: me.onTextfieldChange,
                                    scope: me
                                }
                            }
                        }
                    ]
                },
                {
                    xtype: 'gridpanel',
                    flex: 1,
                    margins: '3 3 3 3',
                    id: 'gridServicios2',
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'fecharegistro',
                            text: 'Fecha y Hora',
                            flex: 6
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'nombres',
                            text: 'Operario',
                            flex: 6
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'servicios',
                            text: 'Servicios',
                            flex: 12
                        },
                        {
                            xtype: 'numbercolumn',
                            align: 'right',
                            dataIndex: 'total',
                            text: 'Costo',
                            flex: 4,
                            format: '0,000'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'fechaentrega',
                            text: 'Salida',
                            flex: 6
                        },
                        {
                            xtype: 'gridcolumn',
                            align: 'right',
                            dataIndex: 'tiempo',
                            text: 'Tiempo',
                            flex: 4
                        }
                    ]
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    flex: 1,
                    dock: 'bottom',
                    items: [
                        {
                            xtype: 'buttongroup',
                            title: 'Impresión',
                            columns: 3,
                            items: [
                                {
                                    xtype: 'button',
                                    iconCls: 'icon-pdf',
                                    listeners: {
                                        click: {
                                            fn: me.onButtonClick11,
                                            scope: me
                                        }
                                    }
                                },
                                {
                                    xtype: 'button',
                                    iconCls: 'icon-excel',
                                    listeners: {
                                        click: {
                                            fn: me.onButtonClick21,
                                            scope: me
                                        }
                                    }
                                }
                            ]
                        },
                        {
                            xtype: 'tbfill'
                        },
                        {
                            xtype: 'buttongroup',
                            columns: 1,
                            layout: {
                                columns: 1,
                                type: 'table'
                            },
                            items: [
                                {
                                    xtype: 'button',
                                    iconCls: 'icon-door_out',
                                    text: 'Salir',
                                    listeners: {
                                        click: {
                                            fn: me.onButtonClickSalir11,
                                            scope: me
                                        }
                                    }
                                }
                            ]
                        }
                    ]
                }
            ],
            listeners: {
                show: {
                    fn: me.onWindowShow,
                    scope: me
                }
            }
        });

        me.callParent(arguments);
    },

    onTextfieldChange: function(field, newValue, oldValue, eOpts) {
        this.traerServicios();
    },

    onButtonClick11: function(button, e, eOpts) {
        var grid=this.grid

        var callback=function(records, operation, succes){

            try{                            
                var result = Ext.decode(operation.response.responseText);        
                siadno.descargarPostConsulta(result);
            }catch(e){            
                if(!Ext.isEmpty(e.message)){
                    Ext.MessageBox.alert('Error codificar la respuesta', e.message);
                }else{
                    Ext.MessageBox.alert('Error codificar la respuesta', e);
                }        
            }

        }

        grid.getStore().getProxy().extraParams.pdf=1;
        grid.getStore().getProxy().extraParams.c=Ext.Number.randomInt(0, 1500000000);
        grid.getStore().load({scope:this, callback:callback});
        grid.getStore().getProxy().extraParams.pdf=0;
    },

    onButtonClick21: function(button, e, eOpts) {
        var grid=this.grid

        var callback=function(records, operation, succes){
            try{                    
                var result = Ext.decode(operation.response.responseText);        
                siadno.descargarPostConsulta(result);
            }catch(e){            
                if(!Ext.isEmpty(e.message)){
                    Ext.MessageBox.alert('Error codificar la respuesta', e.message);
                }else{
                    Ext.MessageBox.alert('Error codificar la respuesta', e);
                }        
            }
        }

        grid.getStore().getProxy().extraParams.excel=1;
        grid.getStore().getProxy().extraParams.c=Ext.Number.randomInt(0, 1500000000);
        grid.getStore().load({scope:this, callback:callback});
        grid.getStore().getProxy().extraParams.excel=0;
    },

    onButtonClickSalir11: function(button, e, eOpts) {
        this.close();
    },

    onWindowShow: function(component, eOpts) {
        var clase=Ext.ClassManager.get("siadno.store.resumenplaca.servicios");
        if(Ext.isEmpty(clase)){
            Ext.define('siadno.store.resumenplaca.servicios', {
                extend: 'Ext.data.Store',

                constructor: function(cfg) {
                    var me = this;
                    cfg = cfg || {};
                    me.callParent([Ext.apply({
                        storeId: Ext.id(),
                        pageSize: 7,
                        proxy: {
                            extraParams:{accion:101},
                            type: 'ajax',
                            url: 'clases/interfaces/InterfazServiciosResumenPlaca.php',
                            reader: {
                                type: 'json',
                                idProperty: 'idservicio',
                                messageProperty: 'msg',
                                root: 'data'
                            }
                        },
                        fields: [
                        {
                            name: 'idservicio'
                        },
                        {
                            name: 'fecharegistro'                    
                        },
                        {
                            name: 'fechaentrega'
                        },
                        {
                            name: 'nombres'
                        },
                        {
                            name: 'tiempo'
                        },
                        {
                            name: 'servicios'
                        },
                        {
                            name: 'total'
                        }
                        ]
                    }, cfg)]);
                }
            });
        }



        this.placa=Ext.ComponentQuery.query('ServiciosOtrosResumenPlaca textfield')[0];
        this.grid=Ext.ComponentQuery.query('ServiciosOtrosResumenPlaca grid')[0];
        this.grid.reconfigure(Ext.create('siadno.store.resumenplaca.servicios'));

        //this.traerServicios();
    },

    traerServicios: function() {
        this.grid.getStore().getProxy().extraParams.placa=this.placa.getValue();
        this.grid.getStore().load();
    }

});