/*
 * File: app/view/administracion/liquidacion/rubros.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('siadno.view.administracion.liquidacion.rubros', {
    extend: 'Ext.window.Window',
    alias: 'widget.AdministracionLiquidacionRubros',

    height: 480,
    width: 640,
    resizable: false,
    layout: {
        align: 'stretch',
        type: 'vbox'
    },
    closable: false,
    iconCls: 'icon-basket',
    title: 'Administración de Servicios y tarifas',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    width: 628,
                    bodyPadding: 10,
                    items: [
                        {
                            xtype: 'combobox',
                            anchor: '100%',
                            fieldLabel: 'Tipo de Servicio',
                            name: 'idtiporubro',
                            displayField: 'descripcion',
                            queryMode: 'local',
                            valueField: 'idtiporubro',
                            listeners: {
                                select: {
                                    fn: me.onComboboxSelect1,
                                    scope: me
                                }
                            }
                        }
                    ]
                },
                {
                    xtype: 'gridpanel',
                    flex: 1,
                    store: 'dumyStore',
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                if(Ext.isEmpty(value)){
                                    return "<font style='color:gray'>--Nuevo Rubro--</font>";    
                                }

                                return value;
                            },
                            dataIndex: 'descripcion',
                            text: 'Servicio',
                            flex: 3,
                            editor: {
                                xtype: 'textfield',
                                allowBlank: false
                            }
                        },
                        {
                            xtype: 'gridcolumn',
                            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                var columna=this.columns[colIndex];
                                var ind=columna.getEditor().getStore().findExact('idtipoautomotor', value);

                                if(value==0 || ind==-1){
                                    return "<font style='color:gray'>--N.D--</font>";    
                                }
                                var registro=columna.field.store.getAt(ind);
                                return registro.get('descripcion');
                            },
                            dataIndex: 'idtipoautomotor',
                            text: 'Tipo Automotor',
                            flex: 2,
                            editor: {
                                xtype: 'combobox',
                                allowBlank: false,
                                displayField: 'descripcion',
                                queryMode: 'local',
                                valueField: 'idtipoautomotor'
                            }
                        },
                        {
                            xtype: 'numbercolumn',
                            dataIndex: 'valorunitario',
                            text: 'Valor Unitario',
                            flex: 1,
                            format: '0,000',
                            editor: {
                                xtype: 'numberfield',
                                allowBlank: false,
                                allowDecimals: false,
                                minValue: 1
                            }
                        },
                        {
                            xtype: 'numbercolumn',
                            dataIndex: 'porcentajeiva',
                            text: 'Porcentaje IVA',
                            flex: 1,
                            format: '0,000',
                            editor: {
                                xtype: 'numberfield',
                                allowBlank: false,
                                allowDecimals: false,
                                maxValue: 100,
                                minValue: 0
                            }
                        },
                        {
                            xtype: 'booleancolumn',
                            dataIndex: 'estado',
                            text: 'Activo?',
                            flex: 1,
                            falseText: 'In Activo',
                            trueText: 'Activo',
                            undefinedText: 'No Definido',
                            editor: {
                                xtype: 'checkboxfield',
                                name: 'estado',
                                boxLabel: 'Activo?'
                            }
                        },
                        {
                            xtype: 'booleancolumn',
                            dataIndex: 'visible',
                            text: 'Visible?',
                            flex: 1,
                            falseText: 'NO',
                            trueText: 'SI',
                            undefinedText: '??',
                            editor: {
                                xtype: 'checkboxfield',
                                name: 'estado',
                                boxLabel: 'Visible?'
                            }
                        }
                    ],
                    selModel: Ext.create('Ext.selection.RowModel', {

                    }),
                    plugins: [
                        Ext.create('Ext.grid.plugin.RowEditing', {

                        })
                    ],
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'bottom',
                            items: [
                                {
                                    xtype: 'buttongroup',
                                    title: 'Acciones',
                                    columns: 5,
                                    layout: {
                                        columns: 2,
                                        type: 'table'
                                    },
                                    items: [
                                        {
                                            xtype: 'button',
                                            accion: 'nuevo',
                                            iconCls: 'icon-page_add',
                                            text: 'Nuevo',
                                            listeners: {
                                                click: {
                                                    fn: me.onButtonClickNuevo,
                                                    scope: me
                                                }
                                            }
                                        },
                                        {
                                            xtype: 'button',
                                            accion: 'guardar',
                                            iconCls: 'icon-page_save',
                                            text: 'Guardar',
                                            listeners: {
                                                click: {
                                                    fn: me.onButtonClickGuardar,
                                                    scope: me
                                                }
                                            }
                                        },
                                        {
                                            xtype: 'button',
                                            iconCls: 'icon-page_cancel',
                                            text: 'Cancelar',
                                            listeners: {
                                                click: {
                                                    fn: me.onButtonClickCancelar,
                                                    scope: me
                                                }
                                            }
                                        },
                                        {
                                            xtype: 'button',
                                            aacion: 'borrar',
                                            iconCls: 'icon-page_delete',
                                            text: 'Borrar',
                                            listeners: {
                                                click: {
                                                    fn: me.onButtonClickBorrar,
                                                    scope: me
                                                }
                                            }
                                        }
                                    ]
                                },
                                {
                                    xtype: 'tbfill'
                                },
                                {
                                    xtype: 'buttongroup',
                                    columns: 1,
                                    layout: {
                                        columns: 1,
                                        type: 'table'
                                    },
                                    items: [
                                        {
                                            xtype: 'button',
                                            iconCls: 'icon-door_out',
                                            text: 'Salir',
                                            listeners: {
                                                click: {
                                                    fn: me.onButtonClickSalir,
                                                    scope: me
                                                }
                                            }
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ],
            listeners: {
                beforeshow: {
                    fn: me.onWindowBeforeShow,
                    scope: me
                }
            }
        });

        me.callParent(arguments);
    },

    onComboboxSelect1: function(combo, records, eOpts) {
        this.cargarLista();
    },

    onButtonClickNuevo: function(button, e, eOpts) {
        var combos=Ext.ComponentQuery.query('AdministracionLiquidacionRubros combo');

        var idTipoRubro=combos[0].getValue();

        var grid=Ext.ComponentQuery.query('AdministracionLiquidacionRubros grid')[0];
        siadno.nuevoRegistroGrid(grid,'idrubro', {idtiporubro:idTipoRubro});
    },

    onButtonClickGuardar: function(button, e, eOpts) {
        var grid=Ext.ComponentQuery.query('AdministracionLiquidacionRubros grid')[0];         
        siadno.enviarCambiosGrid(grid, null, 'idrubro');            
    },

    onButtonClickCancelar: function(button, e, eOpts) {
        var grid=Ext.ComponentQuery.query('AdministracionLiquidacionRubros grid')[0];
        siadno.rollbackCambiosGrid(grid);         
    },

    onButtonClickBorrar: function(button, e, eOpts) {
        var grid=Ext.ComponentQuery.query('AdministracionLiquidacionRubros grid')[0];
        siadno.borrarRegistroGrid(grid, null, 'idrubro');    
    },

    onButtonClickSalir: function(button, e, eOpts) {
        this.close();
    },

    onWindowBeforeShow: function(component, eOpts) {
        var clase=Ext.ClassManager.get("siadno.store.administracion.liquidacion.tiposrubro");
        if(Ext.isEmpty(clase)){
            Ext.define('siadno.store.administracion.liquidacion.tiposrubro', {
                extend: 'Ext.data.Store',

                constructor: function(cfg) {
                    var me = this;
                    cfg = cfg || {};
                    me.callParent([Ext.apply({
                        storeId: Ext.id(),
                        idLocal: -1,
                        proxy: {
                            type: 'ajax',
                            url: 'clases/interfaces/mantenimiento/local/liquidacion/InterfazRubros.php',
                            extraParams:{accion:102},
                            reader: {
                                type: 'json',
                                idProperty: 'idresoluciontarifa',
                                messageProperty: 'msg',
                                root: 'data'
                            }
                        },
                        fields: [
                        {
                            name: 'idtiporubro'
                        },
                        {
                            name: 'descripcion'
                        },
                        {
                            name: 'estado',
                            type: 'boolean'
                        }
                        ]
                    }, cfg)]);
                }
            });
        }

        clase=Ext.ClassManager.get("siadno.store.administracion.liquidacion.rubros");
        if(Ext.isEmpty(clase)){
            Ext.define('siadno.store.administracion.liquidacion.rubros', {
                extend: 'Ext.data.Store',

                constructor: function(cfg) {
                    var me = this;
                    cfg = cfg || {};
                    me.callParent([Ext.apply({
                        storeId: Ext.id(),
                        idLocal: -1,
                        proxy: {
                            type: 'ajax',
                            url: 'clases/interfaces/mantenimiento/local/liquidacion/InterfazRubros.php',                    
                            reader: {
                                type: 'json',
                                idProperty: 'idrubro',
                                messageProperty: 'msg',
                                root: 'data'
                            }
                        },
                        fields: [
                        {
                            name: 'idrubro'
                        },
                        {
                            name: 'idtiporubro'
                        },
                        {
                            name: 'idtipoautomotor'
                        },
                        {
                            name: 'descripcion'
                        },
                        {
                            name: 'porcentajeiva'
                        },
                        {

                            name: 'valorunitario'
                        },
                        {
                            name: 'estado',
                            type: 'boolean'
                        },
                        {
                            name: 'visible',
                            type: 'boolean'
                        }
                        ]
                    }, cfg)]);
                }
            });
        }

        clase=Ext.ClassManager.get("siadno.store.administracion.liquidacion.tiposautomotor2");
        if(Ext.isEmpty(clase)){
            Ext.define('siadno.store.administracion.liquidacion.tiposautomotor2', {
                extend: 'Ext.data.Store',

                constructor: function(cfg) {
                    var me = this;
                    cfg = cfg || {};
                    me.callParent([Ext.apply({
                        storeId: Ext.id(),
                        idLocal: -1,
                        proxy: {
                            extraParams:{accion:103},
                            type: 'ajax',
                            url: 'clases/interfaces/mantenimiento/local/liquidacion/InterfazRubros.php',
                            reader: {
                                type: 'json',
                                idProperty: 'idcombo',
                                messageProperty: 'msg',
                                root: 'data'
                            }
                        },
                        fields: [
                        {
                            name: 'idtipoautomotor'
                        },
                        {
                            name: 'descripcion'
                        },
                        {
                            name: 'estado',
                            type: 'boolean'
                        }
                        ]
                    }, cfg)]);
                }
            });
        }



        combo=Ext.ComponentQuery.query('AdministracionLiquidacionRubros combobox[name=idtiporubro]')[0];
        combo.bindStore(Ext.create('siadno.store.administracion.liquidacion.tiposrubro'));
        combo.getStore().load(); 

        var grid=Ext.ComponentQuery.query('AdministracionLiquidacionRubros grid')[0];
        grid.reconfigure(Ext.create('siadno.store.administracion.liquidacion.rubros'));
        grid.getStore().load();

        columna=grid.columns[1];
        columna.getEditor().bindStore(Ext.create('siadno.store.administracion.liquidacion.tiposautomotor2'));
        columna.getEditor().getStore().load();
    },

    cargarLista: function() {
        var combos=Ext.ComponentQuery.query('AdministracionLiquidacionRubros combo');

        var idTipoRubro=combos[0].getValue();

        var grid=Ext.ComponentQuery.query('AdministracionLiquidacionRubros grid')[0];
        grid.reconfigure(Ext.create('siadno.store.administracion.liquidacion.rubros'));
        grid.getStore().getProxy().extraParams={idtiporubro:idTipoRubro};
        grid.getStore().load();

    }

});