/*
 * File: app/view/sistema/autenticacion.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('siadno.view.sistema.autenticacion', {
    extend: 'Ext.window.Window',
    alias: 'widget.SistemaAutenticacion',

    draggable: false,
    height: 140,
    width: 248,
    layout: {
        type: 'fit'
    },
    closable: false,
    iconCls: 'icon-key_go',
    title: 'Autenticacion',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    bodyPadding: 10,
                    url: 'clases/interfaces/InterfazAutenticacion.php',
                    items: [
                        {
                            xtype: 'textfield',
                            afterLabelTextTpl: '<span style="color:red;font-weight:bold" data-qtip="Required">*</span>',
                            anchor: '100%',
                            id: 'miid2',
                            fieldLabel: 'Usuario',
                            msgTarget: 'side',
                            name: 'login'
                        },
                        {
                            xtype: 'textfield',
                            afterLabelTextTpl: '<span style="color:red;font-weight:bold" data-qtip="Required">*</span>',
                            anchor: '100%',
                            id: 'miid3',
                            fieldLabel: 'Contraseña',
                            msgTarget: 'side',
                            name: 'password',
                            inputType: 'password'
                        }
                    ]
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'bottom',
                    items: [
                        {
                            xtype: 'tbfill'
                        },
                        {
                            xtype: 'buttongroup',
                            columns: 2,
                            layout: {
                                columns: 2,
                                type: 'table'
                            },
                            items: [
                                {
                                    xtype: 'button',
                                    accion: 'salir',
                                    iconCls: 'icon-accept',
                                    text: 'Aceptar',
                                    listeners: {
                                        click: {
                                            fn: me.onButtonAceptar,
                                            scope: me
                                        }
                                    }
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onButtonAceptar: function(button, e, eOpts) {

        var crearMenu=function(callbackParams, result){     
            if(result.success===true){
                this.close();                
            }else{
                return;
            }

            if(!Ext.isEmpty(esTableta) && esTableta==1){                
                siadno.crearTablet();
            }else
            {        
                var task = {
                    run: siadno.crearMenu,
                    interval: 3600000 //60 minutos
                };

                siadno.menuTimer = new Ext.util.TaskRunner();
                siadno.menuTimer.start(task);        
                var body=Ext.getBody();            
                body.createChild("<APPLET id='appletImpresion' CODE='co.com.siadno.Impresora.class' ARCHIVE='clases/IO/Impresion/appletImpresion/dist/appletImpresion.jar' WIDTH=0 HEIGHT=0></APPLET>");        
                siadno.impresoras=Ext.get('appletImpresion').dom;        
            }       
        };
        siadno.enviarFormulario.call(this, false, 'SistemaAutenticacion form', null, crearMenu);
    }

});