/*
 * File: app/view/sistema/cierre.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('siadno.view.sistema.cierre', {
    extend: 'Ext.window.Window',
    alias: 'widget.SistemaCierre',

    draggable: false,
    height: 125,
    width: 200,
    layout: {
        type: 'fit'
    },
    closable: false,
    iconCls: 'icon-door_out',
    title: 'Salida del Sistema',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'bottom',
                    items: [
                        {
                            xtype: 'buttongroup',
                            columns: 2,
                            layout: {
                                columns: 2,
                                type: 'table'
                            },
                            items: [
                                {
                                    xtype: 'button',
                                    accion: 'salir',
                                    iconCls: 'icon-accept',
                                    text: 'Aceptar',
                                    listeners: {
                                        click: {
                                            fn: me.onButtonAceptar,
                                            scope: me
                                        }
                                    }
                                }
                            ]
                        },
                        {
                            xtype: 'tbfill'
                        },
                        {
                            xtype: 'buttongroup',
                            columns: 2,
                            layout: {
                                columns: 2,
                                type: 'table'
                            },
                            items: [
                                {
                                    xtype: 'button',
                                    accion: 'salir',
                                    iconCls: 'icon-cancel',
                                    text: 'Cancelar',
                                    listeners: {
                                        click: {
                                            fn: me.onButtonSalir,
                                            scope: me
                                        }
                                    }
                                }
                            ]
                        }
                    ]
                }
            ],
            items: [
                {
                    xtype: 'form',
                    bodyPadding: 10,
                    url: 'clases/interfaces/InterfazCierre.php',
                    items: [
                        {
                            xtype: 'label',
                            text: 'Está seguro de querer salir del sistema?'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onButtonAceptar: function(button, e, eOpts) {
        var crearMenu=function(callbackParams, result){    
            var viewport=Ext.ComponentQuery.query('myviewport')[0];
            viewport.destroy();    
            var ventanas=Ext.ComponentQuery.query('window');    
            for(var i in ventanas){        
                try{            
                    ventanas[i].close();
                }catch(e){
                    //Dummy try, para errores en el cerrado
                }        
            }    
            siadno.menuTimer.stopAll();
            var interfazAutenticacion=Ext.create('siadno.view.sistema.autenticacion');
            interfazAutenticacion.show();     
        };
        siadno.enviarFormulario.call(this, false, 'SistemaCierre form', null, crearMenu);
    },

    onButtonSalir: function(button, e, eOpts) {
        this.close();
    }

});