/*
 * File: app/store/mantenimiento/privado/modulosenperfil.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('siadno.store.mantenimiento.privado.modulosenperfil', {
    extend: 'Ext.data.TreeStore',

    requires: [
        'siadno.model.mantenimiento.privado.modulo'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            model: 'siadno.model.mantenimiento.privado.modulo',
            storeId: 'MyJsonTreeStore1',
            defaultRootId: '-1',
            nodeParam: 'idmodulo',
            root: {
                nombre: 'modulos',
                idmodulo: -1,
                expanded: true
            },
            proxy: {
                type: 'ajax',
                extraParams: {
                    accion: 2003
                },
                url: 'clases/interfaces/mantenimiento/local/permisos/InterfazPerfiles.php',
                reader: {
                    type: 'json',
                    idProperty: 'idmodulo',
                    messageProperty: 'msg',
                    root: 'data'
                }
            }
        }, cfg)]);
    }
});