/*
 * File: app/view/administracion/local/auditoria/aseguramiento.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('siadno.view.administracion.local.auditoria.aseguramiento', {
    extend: 'Ext.window.Window',
    alias: 'widget.AdministracionLocalAuditoriaAseguramiento',

    VERIFICAR_HASH: 101,
    SUBIR_P12: '102',
    FIRMAR_TABLA: '101',
    height: 509,
    width: 800,
    layout: {
        align: 'stretch',
        type: 'hbox'
    },
    closable: false,
    iconCls: 'icon-database_key',
    title: 'Firma y Aseguramiento de la Base de Datos',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    flex: 2,
                    bodyPadding: 10,
                    url: 'clases/interfaces/mantenimiento/local/auditoria/InterfazAseguramiento.php',
                    items: [
                        {
                            xtype: 'displayfield',
                            anchor: '100%',
                            value: 'Mediante el aseguramiento de datos se consigue verificar que únicamente el sistema de información inserta y modifica registros en la base de datos (BD). Dicha verificación se consigue gracias al estampado de una firma digital basada en <a href=’http://es.wikipedia.org/wiki/Firma_digital’>criptografía de clave pública o asimétrica</a> por parte del sistema en cada uno de los registros insertados o modificados. Esto permite detectar cambios en la información ocasionados por virus informáticos, fallas de hardware o modificaciones no autorizadas fuera del sistema, además posibilitará la expedición de un certificado de autenticidad e integridad de la base de datos.'
                        },
                        {
                            xtype: 'checkboxfield',
                            anchor: '100%',
                            fieldLabel: '',
                            name: 'verificacion1',
                            boxLabel: '<b>Término de funcionamiento 1: </b>Entiendo que el firmado de registros por parte del sistema puede disminuir el rendimiento del sistema en cerca de un 10% a 30% para operaciones de escritura (inserción, modificación y borrado de datos). Y que esta disminución solo será perceptible en momentos de alta congestión y utilización concurrente del sistema.',
                            inputValue: '1',
                            uncheckedValue: '0'
                        },
                        {
                            xtype: 'checkboxfield',
                            anchor: '100%',
                            fieldLabel: '',
                            name: 'verificacion2',
                            boxLabel: '<b>Término de funcionamiento 2: </b>Manifiesto que el certificado de firma digital que proporciono mas adelante se ha expedido con el único propósito de utilizar la llave privada a él vinculado para ejecutar el firmado de registros y que esta llave privada no será utilizada externamente al sistema con ningún otro fin.',
                            inputValue: '1',
                            uncheckedValue: '0'
                        },
                        {
                            xtype: 'checkboxfield',
                            anchor: '100%',
                            fieldLabel: '',
                            name: 'verificacion3',
                            boxLabel: '<b>Término de funcionamiento 3: </b>Entiendo que el sistema tendrá libre acceso a la llave privada vinculada al certificado de firma digital que proporciono mas adelante y que tendrá conocimiento permanente de la clave de seguridad que da acceso a sus funcionalidades de firma y cifrado. Por esta razón manifiesto que dicha llave privada no es utilizada para firmar o cifrar datos o documentos sensible o no sensible fuera de este sistema de información',
                            inputValue: '1',
                            uncheckedValue: '0'
                        },
                        {
                            xtype: 'filefield',
                            anchor: '100%',
                            fieldLabel: 'Archvo p12 o pfx',
                            name: 'archivoP12'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: 'Contraseña',
                            name: 'password',
                            inputType: 'password',
                            allowBlank: false,
                            blankText: 'La contraseña del p12 de obligatoria'
                        }
                    ]
                },
                {
                    xtype: 'gridpanel',
                    flex: 1,
                    forceFit: true,
                    store: 'dumyStore',
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'tabla',
                            text: 'Tabla'
                        },
                        {
                            xtype: 'numbercolumn',
                            width: 55,
                            align: 'right',
                            dataIndex: 'registros',
                            text: 'Registros',
                            format: '0,000'
                        },
                        {
                            xtype: 'gridcolumn',
                            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                if(value==0){
                                    return "<font style='color:red'>InCorrecta</font>";    
                                }

                                if(value==1){
                                    return "<font style='color:blue'>Firmado</font>";    
                                }

                                if(value==2){
                                    return "<font style='color:green'>Firmando, espere</font>";    
                                }

                                if(value==3){
                                    return "<font style='color:gray'>Tiempo Agotado</font>";    
                                }


                                return "<font style='color:gray'>No Ejecutada</font>";    
                            },
                            dataIndex: 'firmado',
                            text: 'Firmado'
                        }
                    ]
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    flex: 1,
                    dock: 'bottom',
                    items: [
                        {
                            xtype: 'buttongroup',
                            title: 'Acciones',
                            columns: 4,
                            layout: {
                                columns: 4,
                                type: 'table'
                            },
                            items: [
                                {
                                    xtype: 'button',
                                    iconCls: 'icon-text_signature',
                                    text: 'Firmar y Asegurar Base de Datos',
                                    listeners: {
                                        click: {
                                            fn: me.onButtonClickCheckHash,
                                            scope: me
                                        }
                                    }
                                }
                            ]
                        },
                        {
                            xtype: 'tbfill'
                        },
                        {
                            xtype: 'buttongroup',
                            columns: 2,
                            layout: {
                                columns: 2,
                                type: 'table'
                            },
                            items: [
                                {
                                    xtype: 'button',
                                    iconCls: 'icon-door_out',
                                    text: 'Salir',
                                    listeners: {
                                        click: {
                                            fn: me.onButtonClick1,
                                            scope: me
                                        }
                                    }
                                }
                            ]
                        }
                    ]
                }
            ],
            listeners: {
                beforeshow: {
                    fn: me.onWindowBeforeShow,
                    scope: me
                }
            }
        });

        me.callParent(arguments);
    },

    onButtonClickCheckHash: function(button, e, eOpts) {
        var cargarP12=function(btn){    
            if(btn != 'yes'){
                return;
            }

            var firmarDB=function(callbackParams, result){

                var grid=Ext.ComponentQuery.query('AdministracionLocalAuditoriaAseguramiento grid')[0];
                var store=grid.getStore();
                var totalTablas=store.getCount();
                var registro=null;

                var callback=function(params, result, exito){            
                    var registro=grid.getStore().getAt(params.indice);            

                    if(exito){            
                        registro.set('firmado', result.firmado);    
                    }else{
                        registro.set('firmado', 3);    
                    }
                    registro.commit();
                };

                for(var i=totalTablas-1; i>=0; i--){
                    registro=store.getAt(i);
                    registro.set('firmado', 2);    
                    siadno.ajax('clases/interfaces/mantenimiento/local/auditoria/InterfazAseguramiento.php', {timeout: 600000, accion:this.FIRMAR_TABLA, indice:i, tabla:registro.get('tabla')}, callback, {indice:i});    

                }        
            };

            siadno.enviarFormulario.call(this, false, 'AdministracionLocalAuditoriaAseguramiento form', {accion:this.SUBIR_P12}, firmarDB);        
        }

        Ext.MessageBox.confirm(
        'Confirmacion de Actividad',
        'Luego de subir el archivo p12 el sistema procederá a firmar cada registro de cada tabla en la base de datos, este procedimiento puede ser demorado dependiendo de la cantidad de registros en cada tabla y puede impactar negativamente el rendimiento en las demás áreas del sistema mientras se este ejecutando. ¿Desea continuar?',    
        cargarP12,
        this
        );


    },

    onButtonClick1: function(button, e, eOpts) {
        this.close();
    },

    onWindowBeforeShow: function(component, eOpts) {
        var clase=Ext.ClassManager.get("siadno.store.administracion.local.auditoria.aseguramiento");
        if(Ext.isEmpty(clase)){
            Ext.define('siadno.store.administracion.local.auditoria.aseguramiento', {
                extend: 'Ext.data.Store',

                constructor: function(cfg) {
                    var me = this;
                    cfg = cfg || {};
                    me.callParent([Ext.apply({
                        storeId: Ext.id(),
                        idLocal: -1,
                        proxy: {
                            type: 'ajax',
                            url: 'clases/interfaces/mantenimiento/local/auditoria/InterfazAseguramiento.php',
                            reader: {
                                type: 'json',
                                idProperty: 'tabla',
                                messageProperty: 'msg',
                                root: 'data'
                            }
                        },
                        fields: [
                        {
                            name: 'tabla'
                        },
                        {
                            name: 'registros'
                        },
                        {
                            name: 'firmado'
                        }                
                        ]
                    }, cfg)]);
                }
            });
        }




        var grids=Ext.ComponentQuery.query('AdministracionLocalAuditoriaAseguramiento grid');

        var grid=grids[0];
        grid.reconfigure(Ext.create('siadno.store.administracion.local.auditoria.aseguramiento'));
        grid.getStore().load();

        //grid.getStore().load();

        //var grid=grids[1];
        //grid.collapse();
        //grid.expand();
        //grid.reconfigure(Ext.create('siadno.store.administracion.local.auditoria.integridad'));
        //grid.getStore().load();
    }

});